# Generated by Django 3.0.9 on 2020-11-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='username',
            new_name='user',
        ),
    ]
