# Generated by Django 3.0.9 on 2020-11-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_auto_20201107_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='plate_number',
            field=models.CharField(default='ABC5A7', max_length=20),
        ),
        migrations.AlterField(
            model_name='rider',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
